apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: dev-
commonLabels:
  environment: dev
patches:
  - target:
      kind: Deployment
      name: payment-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
replicas:
  - name: payment-service
    count: 1
